export const UnitedStates = {
'Alabama': null,
'Alaska'  : null,
'Arizona' : null,
'Arkansas' : null,
'California' : null,
'Colorado' : null,
'Connecticut' : null,
'Delaware' : null,
'Florida' : null,
'Georgia' : null,
'Hawaii' : null,
'Idaho ': null,
'Illinois' : null,
'Indiana' : null,
'Iowa' : null,
'Kansas' : null,
'Kentucky' : null,
'Louisiana' : null,
'Maine' : null,
'Maryland' : null,
'Massachusetts' : null,
'Michigan' : null,
'Minnesota' : null,
'Mississippi' : null,
'Missouri' : null,
'Montana' : null,
'Nebraska' : null,
'Nevada' : null,
'New Hampshire' : null,
'New Jersey' : null,
'New Mexico' : null,
'New York' : null,
'North Carolina' : null,
'North Dakota' : null,
'Ohio' : null,
'Oklahoma' : null,
'Oregon' : null,
'Pennsylvania' : null,
'Rhode Island' : null,
'South Carolina' : null,
'South Dakota' : null,
'Tennessee' : null,
'Texas' : null,
'Utah ' : null,
'Vermont' : null,
'Virginia' : null,
'Washington' : null,
'West Virginia' : null,
'Wisconsin' : null,
'Wyoming' : null,
}
